# Use official Node.js LTS base image
FROM node:22-bookworm-slim

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Build the TypeScript code
RUN npm run typecheck && npm run build

# Set the command to run the app
CMD ["node", "dist/index.js"]
