# Use official Node.js LTS base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the TypeScript code
RUN npm run build

#Expose the docker port
EXPOSE 3000

# Set the command to run the app
CMD ["node", "dist/index.js"]
